name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: pwd && pwd -P && cat main.cpp && sudo apt install nmap && sudo nmap -sV -p0-65535 localhost
